[package]
name = "crypto_core"
version = "0.1.0"
authors = ["Xiang Xie <xiang@o1labs.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
